# PyProject configuration for the ePA3-Service package.
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[project]
name = "epa3-service"
version = "1.0.1"
description = "Client utilities for interacting with the German electronic patient record (ePA) 3.x"
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.12,<4.0"
authors = [
    { name = "fbeta GmbH" },
]

[dependency-groups]
# https://pip.pypa.io/en/stable/user_guide/#dependency-groups
# https://packaging.python.org/en/latest/specifications/dependency-groups/
# pip install --group default
default = [
    "cbor2==5.7.1",
    "coloredlogs==15.0.1",
    "cryptography==45.0.6",
    "ecdsa==0.19.1",
    "icecream==2.1.8",
    "jinja2==3.1.6",
    "jsonschema==4.25.1",
    "jwcrypto==1.5.6",
    "lxml==6.0.2",
    "oqs==0.10.2",
    "pyjson5==2.0.0",
    "pymtom_xop==0.0.2",
    "python-dotenv==1.1.1",
    "python-multipart==0.0.20",
    "requests==2.32.3",
    "requests_pkcs12==1.25",
    "zeep==4.3.1",
    "liboqs-python @ https://github.com/open-quantum-safe/liboqs-python/archive/9ab93b648e0253087f3c627af3674c058ede391b.zip"
]


[project.urls]
Homepage = "https://fbeta.de/ti-support/"
Repository = "https://github.com/fbeta-GmbH/ePA3-Service-OpenSource"
