# PyProject configuration for the ePA3-Service package.
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[project]
name = "epa3-service"
version = "1.0.1"
description = "Client utilities for interacting with the German electronic patient record (ePA) 3.x"
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.11,<4.0"
authors = [
    { name = "fbeta GmbH" },
]

[dependency-groups]
# https://pip.pypa.io/en/stable/user_guide/#dependency-groups
# https://packaging.python.org/en/latest/specifications/dependency-groups/
# pip install --group default
default = [
    "cbor2==5.6.5",
    "coloredlogs==15.0.1",
    "cryptography==44.0.2",
    "ecdsa==0.19.1",
    "icecream==2.1.4",
    "jinja2==3.1.6",
    "jsonschema==4.23.0",
    "jwcrypto==1.5.6",
    "lxml==5.3.2",
    "oqs==0.10.2",
    "pyjson5==1.6.8",
    "pymtom_xop==0.0.2",
    "python-dotenv==1.1.0",
    "python-multipart==0.0.20",
    "requests==2.32.4",
    "zeep==4.3.1",
    "liboqs-python @ git+https://github.com/open-quantum-safe/liboqs-python.git@9ab93b648e0253087f3c627af3674c058ede391b#egg=liboqs-python"
]


[project.urls]
Homepage = "https://fbeta.de/ti-support/"
Repository = "https://github.com/fbeta-GmbH/ePA3-Service-OpenSource"
